version: '3'
services:
  db:
    build:
      context: ./db
      dockerfile: dev.Dockerfile
    image: readit_db:dev
    ports:
      - "5432:5432"
    restart: always
  backend:
    build:
     context: ./backend
     dockerfile: dev.Dockerfile
    image: readit_backend:dev
    ports:
     - "5000:5000"
    volumes:
     - ./backend:/usr/src/app
    depends_on:
     - db
  frontend:
    build:
     context: ./frontend
     dockerfile: dev.Dockerfile
    image: readit_frontend:dev
    ports:
     - "3000:3000"
     - "9009:9009"
    volumes:
     - ./frontend:/usr/src/app
    environment:
     - NODE_ENV=development
    depends_on:
     - backend
  redis:
    image: "redis:alpine"
